replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorImpl.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/ReplicatorImplTest.java, ui/package.json, ui/src/main/webapp/components/replications/ActionsMenu.js, ui/src/main/webapp/components/replications/AddReplication.js, ui/src/main/webapp/components/replications/ReplicationsContainer.js, ui/src/main/webapp/components/replications/ReplicationsTable.js, ui/src/main/webapp/components/replications/actionsMenu.spec.js, ui/src/main/webapp/components/replications/gql/mutations.js, ui/src/main/webapp/components/replications/gql/queries.js, ui/src/main/webapp/components/replications/replications.js, ui/src/main/webapp/components/sites/Sites.js, ui/yarn.lock
- Upgrade react
- Add contextual menu (based on replication status) that displays cancel/suspend/enable actions.
- Split active and inactive replications into 2 tables.
- Fixes UI tests running twice in a build
@clockard @mcalcote @kcover 
- Create a replication and suspend it.
- Confirm after suspension action menu has `Enable` action.
- Confirm a pending, push in progress, and pull in progress replication has the cancel action.
Fixes #33
=> REP-33 Add UI support for Cancel, Suspend, and Enable

ui/package.json, ui/src/main/webapp/app.js, ui/src/main/webapp/components/Navbar.js, ui/src/main/webapp/components/replications/ReplicationsContainer.js, ui/src/main/webapp/components/replications/__tests__/actionsMenu.spec.js, ui/src/main/webapp/components/sites/Site.js, ui/src/main/webapp/components/sites/__tests__/site.spec.js, ui/yarn.lock
- Adds new component for snackbars when displaying node deletion errors.
- Snackbars dismiss within a certain time and no longer stack on each other. 
- Move tests to `__tests__` directories.
@kcover @clockard @mcalcote 
- Create a node.
- Create a Replication between the local Node and the new Node.
- Try to delete a Node used in the Replication.
- Verify snackbars do not stack directly on each other, dismiss over time, and do not duplicate for the same error. 
Verify hovering over home and node icons on navigation menu show help text
Fixes #34
=> REP-34 Fix snackbar errors for deleting nodes

admin/query/pom.xml, admin/query/src/main/java/org/codice/ditto/replication/admin/query/ReplicationUtils.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/replications/persist/DeleteReplication.java, pom.xml, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicationPersistentStoreImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/persistence/ReplicatorConfigManagerImpl.java, replication-api/src/main/java/org/codice/ditto/replication/api/persistence/ReplicatorConfigManager.java
Changes pulled from https://github.com/connexta/replication/pull/52
- Fixes an issue where a request that was running could have an immediate follow up in the pending requests and the pending request run before the `Last Run` on history was set, meaning all the metacards would be queried again.
- Fixes an issue with karaf configuration delete command not cleaning up replication items.
- Ignore case when creating new replication configs and nodes.
Run `log:set DEBUG org.codice.ditto.replication.api.impl`
- Perform a replication and verify the same replicator request is not added to pending requests if it is running (look at logs).
- Confirm `replication:delete -c -h -m` deletes replication items in solr as well as the config and all metacards/data.
=> Various bug fixes

replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorHistoryImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/SyncHelper.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/ReplicationStatusImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/mcard/ReplicationHistoryAttributes.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/data/ReplicationStatusImplTest.java, replication-api/src/main/java/org/codice/ditto/replication/api/ReplicationStatus.java, replication-api/src/main/java/org/codice/ditto/replication/api/mcard/ReplicationHistory.java
- Records the last modified time of the last metacard to be processed, and uses that as the modified after date as part of the next query when determining the metacard change set to replicate.
Setup a replication and do in order:
- Verify creates.
- Verify updates.
- Verify deletes.
- Verify create, update, and delete at once in the same run.
This was an issue when system time between machines varied. This solution makes it so the query does not rely on a different system time.
For example, if machine A is replicating to B, and machine A time is 1:30, but machine B time is 1:31, machine B will record its last success run at 1:31 and use that as its next query's modified after time. So machine A will receive a query, "give me metadata modified after 1:31", but …
=> Fix missing metadata due to system time differences

distributions/replication-dominion/src/main/java/org/codice/ditto/replication/dominion/options/ReplicationOptions.java, pom.xml
It fixes the timing issue during integration testing by updating the codice-test and ddf dependencies to take advantage of their fix for the issue.
@peterhuffer @kcover @clockard @mcalcote 
build passing
Fixes #64
=> [0.2.x] REP-64 Addresses a timing issue in itests

admin/query/pom.xml, admin/query/src/main/java/org/codice/ditto/replication/admin/query/ReplicationUtils.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/fields/ReplicationSiteField.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/persist/CreateReplicationSite.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/persist/UpdateReplicationSite.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/ReplicationUtilsTest.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/sites/persist/CreateReplicationSiteTest.java, distributions/test/itests/src/test/java/org/codice/ditto/replication/admin/query/ITReplicationQuery.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/HybridStore.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorStoreFactoryImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/persistence/SiteManagerImpl.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/persistence/SiteManagerImplTest.java, ui/src/main/webapp/components/sites/AddSite.js, ui/src/main/webapp/components/sites/gql/mutations.js
Add root context to sites so replication works with systems with non default root contexts
Install and create a new site.
- verify that there is a root context field that is defaulted to 'services'
- verify that after creating the site the url shows the context
- verify that replication still works
Fixes #77
=> REP-77 Add root context to sites

admin/query/src/main/java/org/codice/ditto/replication/admin/query/ReplicationUtils.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/replications/fields/ReplicationField.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/fields/ReplicationSiteField.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/AbstractPersistable.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/persistence/ReplicationPersistentStore.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/data/AbstractPersistableTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/persistence/ReplicationPersistentStoreTest.java, replication-api/src/main/java/org/codice/ditto/replication/api/data/Persistable.java
Adds a modified time field to configs and sites and allows it to be read
through the graphql endpoint. Also makes the version of configs and sites readable from the graphql endpoint.
@peterhuffer @clockard @paouelle 
Install replication.
create sites and configurations.
query the graphql endoint for sites and configurations.
verify they contain accurate modified dates and versions.
Fixes #75
=> REP-75 Add modified time to configs and sites

ui/package.json, ui/src/main/webapp/components/common/Confirmable.js, ui/src/main/webapp/components/replications/ReplicationsTable.js, ui/src/main/webapp/components/sites/Site.js
- Cherry picks Node deletion confirmation
- Cherry picks relative time display in configuration table.
- Delete a Node and confirm the confirmation
- Confirm time display in replication table.
=> Node delete confirmation. Relative time display.

admin/query/pom.xml, admin/query/src/main/java/org/codice/ditto/replication/admin/query/ReplicationUtils.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/discover/GetReplicationSites.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/fields/IsDisabledLocalField.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/fields/IsRemoteManagedField.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/fields/RemoteManagedField.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/fields/ReplicationSiteField.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/persist/CreateReplicationSite.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/persist/DeleteReplicationSite.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/persist/UpdateReplicationSite.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/ReplicationUtilsTest.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/sites/persist/DeleteReplicationSiteTest.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/sites/persist/UpdateReplicationSiteTest.java, distributions/test/itests/src/test/java/org/codice/ditto/replication/admin/query/ITReplicationQuery.java, pom.xml, replication-api-impl/pom.xml, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorRunner.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/ReplicationSiteImpl.java, replication-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/ReplicatorRunnerTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/data/ReplicationSiteImplTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/legacy/OldSiteTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/persistence/ReplicationPersistentStoreTest.java, replication-api/src/main/java/org/codice/ditto/replication/api/data/ReplicationSite.java
- Adds support for disabling local replication by site
- Addresses some tech-debt (unit tests, improvements to other graphql functions)
@clockard @paouelle @kcover 
Unit tests.
- Through a GraphiQL client, individually test updating a sites name, hostname, port and rootContext.
=> Support disabling local replication by site

ui/package.json, ui/src/main/webapp/components/replications/ReplicationsTable.js, ui/yarn.lock
Adds a 1 minute interval that will update the relative time display of replication configurations even if their lastRun and lastSuccess dates don't change on polling.
- Setup 2 replications (to verify timers are independent)
- Make sure the date columns tick independently (can put one replication in inactive)
Fixes #87
=> [0.2.x] REP-87 Fix lastRun and lastSuccess not auto updating

admin/query/src/test/java/org/codice/ditto/replication/admin/query/ReplicationUtilsTest.java, replication-api-impl/pom.xml, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/HeartbeaterAndVerifierImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorRunner.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/SyncHelper.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/ReplicationSiteImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/ReplicationStatusImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/SyncRequestImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/legacy/OldSite.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/persistence/SiteManagerImpl.java, replication-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/ReplicatorImplTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/ReplicatorRunnerTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/data/ReplicationSiteImplTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/legacy/OldSiteTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/persistence/ReplicationPersistentStoreTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/persistence/SiteManagerImplTest.java, replication-api/src/main/java/org/codice/ditto/replication/api/Heartbeater.java, replication-api/src/main/java/org/codice/ditto/replication/api/SyncRequest.java, replication-api/src/main/java/org/codice/ditto/replication/api/Verifier.java, replication-api/src/main/java/org/codice/ditto/replication/api/data/ReplicationSite.java, replication-commands/src/main/java/org/codice/ditto/replication/commands/ExistingConfigsCommands.java, replication-commands/src/main/java/org/codice/ditto/replication/commands/RunCommand.java
Modifies the replication site config to add verified-url.
Introduces heartbeater and verifier.
Provided place holder for heartbeat and verification which right now, simply auto-verify the sites by copying the url to the verified one.
@clockard 
@peterhuffer 
@kcover 
Configure replication and make sure it connects normally to start replication.
The replicator was changed to use the verified url when replicating. If this one is null, it will attempt to verify the site first. The current implementation will automatically copy the url to the verified one. A follow up ticket will properly implement the verification and hearbeat process.
Fixes #
=> REP-95 Modified replication site to add verified url.

admin/query/pom.xml, admin/query/src/main/java/org/codice/ditto/replication/admin/query/ReplicationFieldProvider.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/ReplicationMessages.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/ReplicationUtils.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/replications/fields/Iso8601Field.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/replications/fields/ReplicationField.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/replications/fields/ReplicationStatus.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/fields/ReplicationSiteField.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/status/fields/ReplicationStats.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/status/persist/UpdateReplicationStats.java, admin/query/src/main/resources/OSGI-INF/blueprint/blueprint.xml, admin/query/src/test/java/org/codice/ditto/replication/admin/query/ReplicationUtilsTest.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/status/persist/UpdateReplicationStatsTest.java, ui/src/main/webapp/components/replications/ReplicationsTable.js, ui/src/main/webapp/components/replications/__tests__/actionsMenu.spec.js, ui/src/main/webapp/components/replications/gql/mutations.js, ui/src/main/webapp/components/replications/gql/queries.js, ui/src/main/webapp/components/replications/replications.js
- Supports updating a configurations stats by configuration name
- Make back end pass bytes pulled/pushed to front end, and format on front end.
@clockard @kcover 
- Create a replication config that will run normally and verify it still displays correct information
- Create another replication config, disable it, then through a GraphiQL interface, update its stats and verify that it displays correct information in the UI.
This will allow cloud instances to push stats to a fielded node when the cloud owns those replications.
Fixes #95
=> Support updating replication stats

adapters/ion-adapter/pom.xml, adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/IonNodeAdapter.java, adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/IonNodeAdapterFactory.java, adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/spring/ServiceConfig.java, adapters/ion-adapter/src/test/java/com/connexta/replication/adapters/ion/IonNodeAdapterFactoryTest.java, adapters/ion-adapter/src/test/java/com/connexta/replication/adapters/ion/IonNodeAdapterTest.java, adapters/pom.xml, application/pom.xml, application/src/main/java/com/connexta/replication/application/Main.java, pom.xml, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/ReplicationSiteImpl.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/ReplicatorImplTest.java, replication-api/src/main/java/org/codice/ditto/replication/api/data/ReplicationSite.java
Adds an ION NodeAdapter
@kcover @mcalcote 
Create a node that points to an ION mock server.
Create a replication job with the ION node as the destination.
Verify product create requests are getting sent to the ION mock server. (the will not be successful because the mock server always returns failure.)
This is just the initial adapter. The ION ingest endpoint is expected to change and mature so we will need to update this adapter as that happens.
Fixes #102
=> REP-102 Add ION NodeAdapter

pom.xml, replication-api/src/main/java/org/codice/ditto/replication/api/data/ReplicationSite.java, replication-api/src/main/java/org/codice/ditto/replication/api/data/ReplicationStatus.java
- This PR puts in a javadoc generation workaround on master. See https://bugs.openjdk.java.net/browse/JDK-8212233 for more details.
- Fixes javadoc generation warnings
@kcover @clockard 
Run `mvn javadoc:aggregate` locally and verify build success.
Release profile is broken due to javadoc generation error.
=> Fixes javadoc generation

adapters/ddf-adapter/pom.xml, adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/DdfNodeAdapter.java, adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/ResultIterable.java, adapters/ddf-adapter/src/test/java/com/connexta/replication/adapters/ddf/DdfNodeAdapterTest.java, adapters/ddf-adapter/src/test/java/com/connexta/replication/adapters/ddf/ResultIterableTest.java
This commit fixes a bug where no new items are returned when failure
retries are included in a csw query to DDF
Test steps are too long to list here and will likely change soon 😄. See me for information.
Fixes #119
=> REP-119 Fix failure retry query bug

adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/rest/DdfRestClient.java, adapters/ddf-adapter/src/test/java/com/connexta/replication/adapters/ddf/rest/DdfRestClientTest.java, adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/IonNodeAdapter.java, adapters/ion-adapter/src/test/java/com/connexta/replication/adapters/ion/IonNodeAdapterTest.java
*Fixes a bug where initial attempts to replicate a resource to Ion, that
wasn't a text resource, would fail because the file size sent to Ion was
-1.
*Modifies the IonNodeAdapter to consider any create resource response
with a status code in the 200 range to be successful.
- Set up a replication to Ion which will replicate an image.
- Verify that the replication is successful on the first attempt.
Fixes #129
=> REP-129 Fix initial replication to Ion bug

docs/src/main/resources/content/replication-configuring.adoc, replication-api-impl/pom.xml, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/HybridStore.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorStoreFactoryImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/SyncHelper.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/ReplicatorStoreFactoryImplTest.java
Makes the connect and receive timeouts for contacting DDF configurable
via system property.
-Install and configure a DDF for replication.
-Follow the added documentation to configure the replication timeouts
-Install replication
-Set the log level for `org.codice.ditto.replication.api.impl.ReplicatorStoreFactoryImpl` to DEBUG
-Create and run a replication
-Watch for the timeouts to be logged and verify they are the expected values
Fixes #133
=> REP-133 Make connection timeouts configurable

README.md, adapters/ddf-adapter/src/main/java/com/connexta/ion/replication/adapters/ddf/DdfNodeAdapterFactory.java, adapters/ddf-adapter/src/main/java/com/connexta/ion/replication/adapters/ddf/rest/DdfRestClientFactory.java, adapters/ddf-adapter/src/test/java/com/connexta/ion/replication/adapters/ddf/DdfNodeAdapterFactoryTest.java, adapters/ddf-adapter/src/test/java/com/connexta/ion/replication/adapters/ddf/rest/DdfRestClientFactoryTest.java, commons/src/main/java/com/connexta/ion/replication/ReplicationConstants.java, distributions/application/src/main/resources/ssl.properties
Adds and uses a new ssl property to set the cert alias used for https communication.
@kcover @peterhuffer @paouelle @mcalcote 
Create a keystore with a non localhost aliased cert and use it when running replication.
Verify you can connect to a DDF system for replication.
Fixes #139
=> REP-139 Add ssl property for cert alias

adapters/ddf-adapter/src/main/java/com/connexta/ion/replication/adapters/ddf/ResultIterable.java, adapters/ddf-adapter/src/main/java/com/connexta/ion/replication/adapters/ddf/csw/Csw.java, adapters/ddf-adapter/src/main/java/com/connexta/ion/replication/adapters/ddf/csw/CswRecordCollection.java, adapters/ddf-adapter/src/main/java/com/connexta/ion/replication/adapters/ddf/csw/GetRecordsResponseConverter.java, adapters/ddf-adapter/src/main/java/com/connexta/ion/replication/adapters/ddf/rest/RESTService.java, adapters/ion-adapter/src/main/java/com/connexta/ion/replication/adapters/ion/IonNodeAdapterFactory.java, pom.xml, replication-api/src/main/java/com/connexta/ion/replication/api/NodeAdapter.java, replication-api/src/main/java/com/connexta/ion/replication/api/Replicator.java, replication-api/src/main/java/com/connexta/ion/replication/api/data/QueryRequest.java, replication-api/src/main/java/com/connexta/ion/replication/api/data/ReplicationStatus.java, replication-api/src/main/java/com/connexta/ion/replication/api/persistence/DataManager.java, replication-api/src/main/java/com/connexta/ion/replication/api/persistence/ReplicationItemManager.java, replication-api/src/main/java/com/connexta/ion/replication/api/persistence/ReplicatorHistoryManager.java
Fix javadoc to work with latest plugin
Manual javadoc build since CI on a PR will not run the javadoc
Updated the javadoc plugin via dependabot which resulted in stricter javadoc checking.
Some of the javadoc added for interfaces copied from DDF is not very descriptive but I think thats ok for now
=> Fix javadoc to work with latest plugin

pom.xml, replication-api-impl/owasp-suppressions.xml, replication-api-impl/pom.xml, replication-api-impl/src/main/java/com/connexta/ion/replication/api/impl/persistence/ReplicationItemManagerImpl.java
- Upgrades spring-data-solr to address some CVEs
- Remove spring boot parent pom as parent
Solr docker 8.2.0 is not available yet so can't upgrade that container in this PR
@kcover @paouelle @clockard 
- Startup solr and verify creating and deleting a site config works fine.
Fixes #
=> Bump spring-data-solr from 4.0.9.RELEASE to 4.1.0.RC2

README.md, commons/pom.xml, commons/src/main/java/com/connexta/ion/replication/spring/ReplicationProperties.java, pom.xml, replication-api-impl/pom.xml, replication-api-impl/src/main/java/com/connexta/ion/replication/api/impl/ReplicatorRunner.java, replication-api-impl/src/main/java/com/connexta/ion/replication/api/impl/spring/ServiceConfig.java, replication-api-impl/src/test/java/com/connexta/ion/replication/api/impl/ReplicatorRunnerTest.java
It adds new sites property and modifies the replicator runner to skip destination sites that are not configured. If no sites are configured (the default right now), all configurations are handled as we did before making the same configuration works the same way.
@clockard 
@peterhuffer 
@kcover 
- Deploy and start Solr as usual
- Push 2 sites with id xxx1 and xxx2
- Push 2 replication configurations to Solr:
--- unidirectional from site xxx1 to xxx2 with a query 
--- unidirectional from site xxx2 to xxx1 with a different query
- Push 2 application.yaml in Docker:
--- the first configures the new replication.sites property defined as xxx1
--- the second configures the new replication.sites property defined as xxx2
- Deploy 2 replication docker instance each using its own application.yaml
- …
=> DITTO-124 Support for limiting the replication to a set of destination sites

README.md, grafana-dashboard.json
- Add a grafana dashboard file for viewing replication specific metrics
@oconnormi @paouelle @kcover @clockard 
Starting up replication, prometheus, and grafana. Import the dashboard into grafana and run a replication to see the dashboard.
Fixes #
=> Add a grafana dashboard file

adapters/ddf-adapter/src/main/java/com/connexta/ion/replication/adapters/ddf/CqlBuilder.java, adapters/ddf-adapter/src/main/java/com/connexta/ion/replication/adapters/ddf/csw/MetacardMarshaller.java, adapters/ddf-adapter/src/test/java/com/connexta/ion/replication/adapters/ddf/ResultIterableTest.java, pom.xml, replication-api-impl/src/main/java/com/connexta/ion/replication/api/impl/NodeAdapters.java, replication-api-impl/src/main/java/com/connexta/ion/replication/api/impl/persistence/ReplicationItemManagerImpl.java
Bumps fmt-maven-plugin from 2.0.0 to 2.9.
@clockard 
CI
=> Bump fmt-maven-plugin from 2.0.0 to 2.9

adapters/ion-adapter/src/main/java/com/connexta/ion/replication/adapters/ion/IonNodeAdapter.java, adapters/ion-adapter/src/test/java/com/connexta/ion/replication/adapters/ion/IonNodeAdapterTest.java
Includes a correlation ID with ingest requests to ion.
Replicate to Ion and watch the Ion-ingest logs. Look for a "CREATED" response to be logged. A 500 returned to replication is expected, as is a 400 in the Ion-ingest logs after the "CREATED" response.
Fixes #195
=> REP-195 Include correlation ID for Ion ingest

distributions/docker/solr/src/main/docker/Dockerfile, replication-api-impl/pom.xml, replication-api-impl/src/main/java/com/connexta/ion/replication/api/impl/spring/ServiceConfig.java, replication-api-impl/src/main/java/com/connexta/replication/api/impl/data/FilterImpl.java, replication-api-impl/src/main/java/com/connexta/replication/api/impl/data/FilterManagerImpl.java, replication-api-impl/src/main/java/com/connexta/replication/api/impl/persistence/pojo/FilterPojo.java, replication-api-impl/src/main/java/com/connexta/replication/api/impl/persistence/spring/FilterRepository.java, replication-api-impl/src/test/java/com/connexta/replication/api/impl/data/FilterImplTest.java, replication-api-impl/src/test/java/com/connexta/replication/api/impl/data/FilterManagerImplTest.java, replication-api-impl/src/test/java/com/connexta/replication/api/impl/persistence/pojo/FilterPojoTest.java, replication-api-impl/src/test/java/com/connexta/replication/api/impl/persistence/spring/FilterRepositoryIntegrationTest.java, replication-api/src/main/java/com/connexta/replication/api/data/Filter.java, replication-api/src/main/java/com/connexta/replication/api/persistence/FilterManager.java, replication-api/src/main/java/com/connexta/replication/queue/TaskInfo.java, solr-schema/src/main/resources/solr/conf/replication-solr-managed-schema.xml
Adds a filter config object to replication along with the persistence manager and tests to go with it.
@peterhuffer @clockard @paouelle 
CI Build 
Fixes #207
=> REP-207 Add filter config

adapters/ddf-adapter/pom.xml, adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/DdfNodeAdapter.java, adapters/ddf-adapter/src/test/java/com/connexta/replication/adapters/ddf/DdfNodeAdapterTest.java, adapters/ion-adapter/pom.xml, adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/IonNodeAdapter.java, adapters/ion-adapter/src/test/java/com/connexta/replication/adapters/ion/IonNodeAdapterTest.java, commons/src/main/java/com/connexta/replication/data/QueryResponseImpl.java, replication-api-impl/src/main/java/com/connexta/replication/api/impl/Syncer.java, replication-api-impl/src/main/java/com/connexta/replication/api/impl/data/CreateStorageRequestImpl.java, replication-api-impl/src/main/java/com/connexta/replication/api/impl/data/UpdateStorageRequestImpl.java, replication-api-impl/src/test/java/com/connexta/replication/api/impl/SyncerTest.java, replication-api/src/main/java/com/connexta/replication/api/AdapterException.java, replication-api/src/main/java/com/connexta/replication/api/AdapterInterruptedException.java, replication-api/src/main/java/com/connexta/replication/api/NodeAdapter.java, replication-api/src/main/java/com/connexta/replication/api/data/CreateStorageRequest.java, replication-api/src/main/java/com/connexta/replication/api/data/QueryResponse.java, replication-api/src/main/java/com/connexta/replication/api/data/UpdateStorageRequest.java, replication-api/src/main/java/com/connexta/replication/api/data/ddf/DdfMetadataInfo.java
This PR adds support for handling interruptions inside the adapters (DDF and Ion). It also removes the ability to create/update multiple resources which was not used and will not be used in the new architecture.
@peterhuffer 
@kcover 
@clockard 
CI
Fixes #XXXX
=> REP-225 Added support for interruptions to adapters 
