admin/query/pom.xml, admin/query/src/main/java/org/codice/ditto/replication/admin/query/ReplicationUtils.java, distributions/test/itests/pom.xml, distributions/test/itests/src/test/java/org/codice/ditto/replication/admin/query/ITReplicationQuery.java, distributions/test/pom.xml, pom.xml
Creates tests to confirm that the API sends the proper responses. It also fixes an issue I found while creating the tests where the hostname and port of an object were returned as null.
@paouelle @peterhuffer @clockard 
Start an instance of DDF and run the tests.
#8
=> Rep-8 Create API Response Tests

pom.xml
Upgrade DDF and Admin Console versions
@paouelle @kcwire @peterhuffer 
Verify build passes
Build was failing because DDF snapshot dependency was no longer available.
#5
=> REP-5 Upgrade DDF and Admin Console versions

pom.xml, ui/jestsetup.js, ui/package.json, ui/pom.xml, ui/src/main/webapp/components/sites/site.spec.js, ui/yarn.lock
Adds Jest for UI testing and coverage checks.
@paouelle @clockard @kcover
Full build.
#4
=> REP-4 Add UI test runner and coverage check

.github/PULL_REQUEST_TEMPLATE
- To auto close issues, the PR must include `Fixes #XX`.
- Also moves PR template to .github folder
@paouelle @kcover 
N/A
=> Update PR template to help auto close issues

dependency-check-maven-config.xml
Fixes and owasp issue that doesn't apply to us
@kcover @paouelle 
CI build
=> Fix new karaf owasp finding

pom.xml, replication-api-impl/pom.xml, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorHistoryImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorRunner.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/SyncHelper.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/mcard/ReplicationHistoryAttributes.java, replication-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/ReplicatorHistoryImplTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/ReplicatorRunnerTest.java, replication-api/src/main/java/org/codice/ditto/replication/api/ReplicationPersistenceException.java, replication-api/src/main/java/org/codice/ditto/replication/api/ReplicationStatus.java, replication-api/src/main/java/org/codice/ditto/replication/api/ReplicatorHistory.java, replication-api/src/main/java/org/codice/ditto/replication/api/mcard/ReplicationHistory.java, replication-commands/src/main/java/org/codice/ditto/replication/commands/StatusCommand.java
Add scheduling to replication and condense status messages
@peterhuffer @kcover @paouelle
Install replication and create a replication configuration verify after 10min or so that there are some status entries via the replication:status command. 
Fixes #20
=> REP-20 Add scheduling to replication and condense status messages

admin/pom.xml, admin/query/pom.xml, distributions/osgi/features/pom.xml, distributions/osgi/features/replication/pom.xml, distributions/osgi/pom.xml, distributions/pom.xml, distributions/test/itests/pom.xml, distributions/test/pom.xml, docs/pom.xml, pom.xml, replication-api-impl/pom.xml, replication-api/pom.xml, replication-commands/pom.xml, ui/pom.xml
Change project version to 0.2.0-SNAPSHOT since we have added an endpoint/ui
@peterhuffer @paouelle @kcover @mcalcote 
CI Build
=> Change project version to 0.2.0-SNAPSHOT

ui/package.json, ui/yarn.lock
- Adds `yarn audit` security check as part of the build.
- Upgrades jest
@mcalcote @kcover @clockard @paouelle 
Full build.
Fixes #30
=> REP-30 Add UI package security scans

Jenkinsfile
Remove windows build from jenkins file
@kcover @peterhuffer @paouelle 
CI build passes. Only will be able to tell for sure once it is merged into master
=> Remove windows build from jenkins file

ui/package.json
Remove audit check until vulnerabilities (non-critical dev dependencies only) can be resolved. Currently there is no suppressions supported by the audit command and the affected libraries do not have the required version upgrades.
@clockard @kcover 
CI build.
=> Update package.json build script

admin/query/src/test/java/org/codice/ditto/replication/admin/query/ReplicationUtilsTest.java, replication-api-impl/pom.xml, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorHistoryImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorRunner.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/SyncHelper.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/ReplicationStatusImpl.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/ReplicatorHistoryImplTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/ReplicatorImplTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/SyncHelperTest.java, replication-api/src/main/java/org/codice/ditto/replication/api/ReplicationStatus.java, replication-commands/src/main/java/org/codice/ditto/replication/commands/RunCommand.java
Updates the status (item count and bytes transferred) while the replication is running
Ingest a fairly large amount of data such that it will take a minute or so to replicate. Setup a replication job to replicate the ingested data. Observe that the item count and bytes transferred are updated as the job is running before it is completed
Fixes #42
=> REP-42 Update status while processing

pom.xml
- Upgrade DDF version to 2.13.7-SNAPSHOT
@clockard @paouelle @kcover 
Full build.
=> Upgrade DDF version

Jenkinsfile
Adds release capability to the replication pipeline
@peterhuffer @paouelle @mcalcote @kcover 
Right now the best way to test is a good CI build followed by an actual release.
=> Update Jenkins file to include release parameters

replication-api-impl/pom.xml
Fixes the ddf.security.encryption dependency issue
@kcover @peterhuffer @paouelle 
Deploy the kar to an instance of ddf-2.13.6 and verify there are no missing dependency errors
Fixes #50
=> REP-50 Set import version range on ddf.security.encryption

Jenkinsfile
What the title says
@kcover @peterhuffer 
Already tested on jenkins environment
=> Fix Jenkinsfile default parameter values

admin/query/pom.xml, admin/query/src/main/java/org/codice/ditto/replication/admin/query/ReplicationFieldProvider.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/ui/GetUiConfig.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/ui/UiConfigField.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/ui/UiConfigurationFactory.java, admin/query/src/main/resources/OSGI-INF/blueprint/blueprint.xml, admin/query/src/test/java/org/codice/ditto/replication/admin/query/ui/GetUiConfigTest.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/ui/UiConfigFieldTest.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/ui/UiConfigurationFactoryTest.java, pom.xml, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/legacy/LegacyDataConverterTest.java, ui/src/main/webapp/app.js
Adds banners to the UI and adds functionality to the back end to read how to display the banners from a config file.
@peterhuffer @clockard @paouelle @mcalcote 
Contact me for testing details.
Fixes #40
=> REP-40 Add banners to the UI

admin/pom.xml, admin/query/pom.xml, distributions/osgi/features/pom.xml, distributions/osgi/features/replication/pom.xml, distributions/osgi/pom.xml, distributions/pom.xml, distributions/test/itests/pom.xml, distributions/test/pom.xml, docs/pom.xml, pom.xml, replication-api-impl/pom.xml, replication-api/pom.xml, replication-commands/pom.xml, ui/pom.xml
Updates master to the next dev version
@kcover @peterhuffer @paouelle 
CI Build
=> Update development version

README.md
Adds some security/quality badges to our repo readme
@peterhuffer @kcover @mcalcote @paouelle 
No testing needed
Just something fun for our repo that shows our quality
=> Add badges to README.mc

ui/src/main/webapp/components/common/Confirmable.js, ui/src/main/webapp/components/replications/ReplicationsTable.js, ui/src/main/webapp/components/sites/Site.js
- Displays time in Replication tables as relative, ex: 2 minutes ago.
- Adds confirmation for deleting sites.
@clockard @kcover @mcalcote 
- Confirm deleting Nodes
=> Confirm Node deletion

docs/src/main/resources/content/_using/replication-configuring.adoc, docs/src/main/resources/content/_using/replication-installing.adoc, docs/src/main/resources/content/_using/replication-limitations.adoc, docs/src/main/resources/content/_using/replication-running.adoc, docs/src/main/resources/content/_using/replication-updating.adoc
- Removes installing via command line since it requires security manager permissions to do file schema, and an m2 repository to do mvn schema.
- Update installing via deploy directory
@clockard @paouelle @kcover 
Test the doc steps. See me.
=> Update kar deployment docs

Jenkinsfile
Fixes jenkins file variables used in the release process
@paouelle @peterhuffer @kcover
=> Fix jenkinsfile release variables

admin/query/pom.xml, admin/query/src/main/java/org/codice/ditto/replication/admin/query/ReplicationUtils.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/fields/ReplicationSiteField.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/persist/CreateReplicationSite.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/persist/UpdateReplicationSite.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/ReplicationUtilsTest.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/sites/persist/CreateReplicationSiteTest.java, distributions/test/itests/src/test/java/org/codice/ditto/replication/admin/query/ITReplicationQuery.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/HybridStore.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorStoreFactoryImpl.java, ui/src/main/webapp/components/sites/AddSite.js, ui/src/main/webapp/components/sites/gql/mutations.js
=> REP-77 Add root context to sites (#78)

admin/query/pom.xml, admin/query/src/main/java/org/codice/ditto/replication/admin/query/ReplicationUtils.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/discover/GetReplicationSites.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/fields/RemoteManagedField.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/fields/ReplicationSiteField.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/persist/CreateReplicationSite.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/persist/DeleteReplicationSite.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/sites/persist/UpdateReplicationSite.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/ReplicationUtilsTest.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/sites/persist/CreateReplicationSiteTest.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/sites/persist/DeleteReplicationSiteTest.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/sites/persist/UpdateReplicationSiteTest.java, distributions/test/itests/src/test/java/org/codice/ditto/replication/admin/query/ITReplicationQuery.java, pom.xml, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/ReplicationSiteImpl.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/data/ReplicationSiteImplTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/persistence/ReplicationItemManagerTest.java, replication-api/src/main/java/org/codice/ditto/replication/api/data/ReplicationSite.java
Port of https://github.com/connexta/replication/pull/88 excluding the logic in the ReplicationRunner to skip running configurations.
@paouelle @kcover @clockard 
CI build.
=> Support disabling local replication by site

replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorStoreFactoryImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/ReplicationSiteImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/legacy/OldSite.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/ReplicatorStoreFactoryImplTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/data/ReplicationSiteImplTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/legacy/OldSiteTest.java
- Fixes a corrupted Site URL when reading old sites
@clockard @kcover 
- Install latest and ensure replication works.
- Install 0.2.0, create a site and a replication. Upgrade to 0.2.3-SNAPSHOT following the kar upgrade docs. Run the existing replication and verify it works.
Fixes #
=> Fix invalid url when reading old sites

replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/SyncHelper.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/SyncHelperTest.java
This commit fixes a bug where no new items are returned when failure
retries are included in a csw query to DDF
-Install a system based on a released DDF 2.13.x
-Create a replication and set an item up to fail (the only way i know of to do this is to create a cdm     without configuring the resource reader for the same directory).
-Once you have a failed item, ingest a new product through the UI and replicate again.
-Verify the product ingested through the UI was replicated.
Fixes #119
=> [0.2.x] REP-119 Fix failure retry query bug

distributions/application/src/main/resources/application.yml
Updates application config file's solr url
@clockard @kcover @mcalcote 
CI
Fixes #
=> Updates application config file's solr url

adapters/ion-adapter/src/main/java/com/connexta/ion/replication/adapters/ion/IonNodeAdapter.java, replication-api-impl/src/main/java/com/connexta/ion/replication/api/impl/Syncer.java, replication-api-impl/src/test/java/com/connexta/ion/replication/api/impl/SyncerTest.java
Remove title from IonAdapters ingest request.
Addressed a sonarqube finding in the file as well.
@kcover @peterhuffer @paouelle @mcalcote 
Verify replication with Ion still works
Ingest api was changed to remove the title field
Fixes #142
=> REP-142 Remove title from IonAdapters ingest request

admin/query/src/main/java/org/codice/ditto/replication/admin/query/ReplicationFieldProvider.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/queries/GetQueries.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/queries/QueryField.java, admin/query/src/main/resources/OSGI-INF/blueprint/blueprint.xml, admin/query/src/test/java/org/codice/ditto/replication/admin/query/queries/GetQueriesTest.java, dependency-check-maven-config.xml, distributions/test/itests/pom.xml, distributions/test/itests/src/test/java/org/codice/ditto/replication/admin/query/ITReplicationQuery.java, distributions/test/itests/src/test/java/org/codice/ditto/replication/admin/query/requests/QueriesGraphQL.java, distributions/test/itests/src/test/resources/query/queries/query/AllQueries.graphql, pom.xml, replication-api-impl/pom.xml, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/QueryServiceImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/QueryImpl.java, replication-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/QueryServiceImplTest.java, replication-api/src/main/java/org/codice/ditto/replication/api/QueryException.java, replication-api/src/main/java/org/codice/ditto/replication/api/QueryService.java, replication-api/src/main/java/org/codice/ditto/replication/api/data/Query.java, ui/package.json, ui/src/main/webapp/components/queries/gql/queries.js, ui/src/main/webapp/components/replications/AddReplication.js, ui/src/main/webapp/components/replications/QuerySelector.js, ui/yarn.lock
Allows the user to select a pre-saved query when creating a replication so they can use its filter.
install replication, create some queries and test out the new ui component. Get creative and try to break it 😉 . You should also save with one of the created queries and make sure replication will actually work with that filter.
Fixes #136
=> REP-136 Allow the user to use a pre-saved query for replication

admin/query/src/main/java/org/codice/ditto/replication/admin/query/ReplicationUtils.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/replications/fields/ReplicationField.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/replications/persist/CreateReplication.java, admin/query/src/main/java/org/codice/ditto/replication/admin/query/replications/persist/UpdateReplication.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/ReplicationUtilsTest.java, admin/query/src/test/java/org/codice/ditto/replication/admin/query/replications/persist/CreateReplicationTest.java, pom.xml, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/SyncHelper.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/AbstractPersistable.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/ReplicationSiteImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/data/ReplicatorConfigImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/legacy/LegacyDataConverter.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/legacy/OldSite.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/SyncHelperTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/data/AbstractPersistableTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/data/ReplicatorConfigImplTest.java, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/persistence/ReplicationPersistentStoreTest.java, replication-api/src/main/java/org/codice/ditto/replication/api/data/ReplicatorConfig.java, replication-commands/src/main/java/org/codice/ditto/replication/commands/ConfigAddCommand.java, ui/src/main/webapp/components/replications/AddReplication.js, ui/src/main/webapp/components/replications/ReplicationsTable.js, ui/src/main/webapp/components/replications/gql/fragments.js, ui/src/main/webapp/components/replications/gql/mutations.js
Add metadata only replication option
Setup a replication job with the metadata only option checked. 
Verify metadata only replicated. This can be verified by checking that the resource-uri is empty/DNE.
Fixes #148
=> REP-148 Add metadata only replication option

admin/query/pom.xml, dependency-check-maven-config.xml, distributions/osgi/features/replication/src/main/feature/feature.xml, distributions/osgi/security/replication/src/main/resources/replication.policy, distributions/pom.xml, distributions/test/itests/pom.xml, distributions/test/itests/src/test/java/org/codice/ditto/replication/admin/query/ITReplicationQuery.java, pom.xml, replication-api-impl/pom.xml, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/QueryServiceImpl.java, replication-api-impl/src/main/java/org/codice/ditto/replication/api/impl/ReplicatorStoreFactoryImpl.java, replication-api-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, replication-api-impl/src/test/java/org/codice/ditto/replication/api/impl/QueryServiceImplTest.java, ui/pom.xml
Updates DDF version 
Still need to fix itest
Basic replication testing on a DDF 2.16.x
Will need to install the admin console 1.3.2 as well
=> Update replication to work with DDF 2.16.x

Jenkinsfile
Update Jenkins file to account for missing itests
@paouelle @peterhuffer @kcover 
CI tests will not test this. Needs to be in master to test.
=> Update Jenkins file to account for missing itests

pom.xml
- Removes unused plugins
@paouelle @kcover @clockard 
CI
Fixes #
=> Remove asciidoc and package json check

replication-api/src/main/java/com/connexta/replication/queue/CompositeQueue.java, replication-api/src/main/java/com/connexta/replication/queue/CompoundQueue.java, replication-api/src/main/java/com/connexta/replication/queue/DataInfo.java, replication-api/src/main/java/com/connexta/replication/queue/ErrorCode.java, replication-api/src/main/java/com/connexta/replication/queue/MetadataInfo.java, replication-api/src/main/java/com/connexta/replication/queue/OperationType.java, replication-api/src/main/java/com/connexta/replication/queue/PriorityLevel.java, replication-api/src/main/java/com/connexta/replication/queue/Queue.java, replication-api/src/main/java/com/connexta/replication/queue/QueueBroker.java, replication-api/src/main/java/com/connexta/replication/queue/QueueException.java, replication-api/src/main/java/com/connexta/replication/queue/ResourceInfo.java, replication-api/src/main/java/com/connexta/replication/queue/SiteQueue.java, replication-api/src/main/java/com/connexta/replication/queue/Task.java, replication-api/src/main/java/com/connexta/replication/queue/TaskInfo.java, replication-api/src/main/java/com/connexta/replication/queue/ddf/DDFMetadataInfo.java
It defines interfaces for the new queue api which will be used by both query services and workers.
@clockard 
@kcover 
@peterhuffer 
PR build should suffice as no implementation or client exists yet.
Fixes #190
=> REPL-137 First version for the new queue broker API

LICENSE.md, ThreatDragonModels/replication_threat_model.json, adapters/ddf-adapter/src/main/java/com/connexta/ion/replication/adapters/ddf/CqlBuilder.java, adapters/ddf-adapter/src/test/java/com/connexta/ion/replication/adapters/ddf/csw/GetRecordsMessageBodyReaderTest.java, adapters/ion-adapter/src/test/java/com/connexta/ion/replication/adapters/ion/IonNodeAdapterFactoryTest.java, adapters/ion-adapter/src/test/java/com/connexta/ion/replication/adapters/ion/IonNodeAdapterTest.java, commons/src/main/java/com/connexta/ion/replication/spring/ReplicationProperties.java, distributions/application/src/test/java/com/connexta/ion/replication/application/MainTest.java, headerJava.txt, pom.xml, replication-api-impl/src/main/java/com/connexta/ion/replication/api/impl/persistence/ReplicatorConfigManagerImpl.java, replication-api-impl/src/main/java/com/connexta/ion/replication/api/impl/persistence/SiteManagerImpl.java, replication-api/src/main/java/com/connexta/ion/replication/api/persistence/DataManager.java
Enforce headers on java files.
Also adds the threat dragon model and a few cleanup/updates to the parent pom.
@peterhuffer @paouelle @kcover 
CI build
=> Enforce headers on java files.

distributions/docker/replication/src/main/docker/files.xml, distributions/docker/solr/src/main/docker/files.xml
- Fix erroneous file copies of global dependencies that were being copied into target
@clockard @paouelle @kcover 
CI
=> Fix erroneous file copies of global dependencies

distributions/application/pom.xml, docker-compose.yml, pom.xml
- Adds filtering to docker-compose file. Just places the processed file under top level target directory for now.
CI
=> Remove hardcoded versions from docker-compose file

.circleci/config.yml, README.md, adapters/ddf-adapter/pom.xml, pom.xml
Add circle ci builds to replication
Verify circle ci build passes
Fixes #226
=> REP-226 add circle ci builds to replication

Jenkinsfile, adapters/ddf-adapter/pom.xml, pom.xml, replication-api-impl/src/main/java/com/connexta/replication/api/impl/data/AbstractPersistable.java, replication-api-impl/src/main/java/com/connexta/replication/api/impl/persistence/pojo/ItemPojo.java, replication-api-impl/src/main/java/com/connexta/replication/api/impl/spring/ServiceConfig.java, replication-api/src/main/java/com/connexta/replication/api/persistence/ReplicationItemManager.java
Fixes javadoc
Fixes an owasp finding
Updates some dependencies
@peterhuffer @paouelle @kcover 
CI Build
=> Java Doc Fix

adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/DdfMetadata.java, adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/DdfNodeAdapter.java, adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/csw/CswRecordConverter.java, adapters/ddf-adapter/src/main/java/com/connexta/replication/adapters/ddf/csw/MetacardMarshaller.java, adapters/ddf-adapter/src/test/java/com/connexta/replication/adapters/ddf/DdfNodeAdapterTest.java, adapters/ddf-adapter/src/test/java/com/connexta/replication/adapters/ddf/csw/CswRecordConverterTest.java, adapters/ddf-adapter/src/test/java/com/connexta/replication/adapters/ddf/csw/GetRecordsResponseConverterTest.java, adapters/ddf-adapter/src/test/java/com/connexta/replication/adapters/ddf/csw/MetacardMarshallerTest.java, adapters/ddf-adapter/src/test/java/com/connexta/replication/adapters/ddf/rest/DdfRestClientTest.java, adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/IonNodeAdapter.java, adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/IonNodeAdapterFactory.java, adapters/ion-adapter/src/test/java/com/connexta/replication/adapters/ion/IonNodeAdapterTest.java
Adds metadata to Ion create requests
**Attachment name still needs approval from CDR team**
@peterhuffer @paouelle @kcover 
Manual test in integration environment
Fixes #214
=> REP-214 Add metadata to Ion create requests

.circleci/config.yml, pom.xml
Update circle ci config to match template
Differences from the template:
- Workflow has filters on individual jobs
- Sonar added for pr builds
- M2 caching added
- Workspace caching added
Items jenkins pipeline does that circle ci currently does not
- Run end to end tests
- Release 
Passing circle ci build
current circle ci doesn't conform to the template
=> Update circle ci config to match template

.circleci/config.yml, pom.xml
What does this PR do?
Fix circle ci deploy step
Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
How should this be tested? (List steps with links to updated documentation)
Passing circle ci with deploy
gh
=> Remove deploy/release steps from circle ci

adapters/ion-adapter/src/test/java/com/connexta/replication/adapters/ion/IonNodeAdapterTest.java
Fixes testing from command line where the same thread is used to test all classes.
@kcover 
@peterhuffer 
Fixes #XXXX
=> REPL-150 Made sure to clear interruptions during test so they do not bleed into the next tested class

.circleci/config.yml, README.md, adapters/ion-adapter/src/main/java/com/connexta/replication/adapters/ion/IonNodeAdapter.java, adapters/ion-adapter/src/test/java/com/connexta/replication/adapters/ion/IonNodeAdapterTest.java
Adds the metadata modified time to ingest requests for ion.
start the replication stack and ingest something into ion.
Fixes #264
=> REP-264 Add modified time to Ion ingest requests

README.md
Adds details to the readme to make it a decent guide for anyone trying to use the replication service.
=> Upgrade ReadMe

pom.xml, query/src/main/java/com/connexta/replication/query/QueryManager.java, query/src/main/java/com/connexta/replication/query/QueryService.java, query/src/test/java/com/connexta/replication/query/QueryManagerTest.java, replication-api-impl/pom.xml, replication-api-impl/src/main/java/com/connexta/replication/api/impl/queue/memory/MemorySiteQueue.java, replication-api-impl/src/main/java/com/connexta/replication/api/impl/queue/memory/MemoryTask.java, replication-api-impl/src/main/java/com/connexta/replication/api/impl/worker/Worker.java
Fix some sonar and owasp findings
@kcover 
CI Build passes
=> Fix sonar and owasp findings

distributions/osgi/features/replication/pom.xml, distributions/osgi/features/replication/src/main/feature/feature.xml, pom.xml, replication-commands/pom.xml, ui/pom.xml
Updates replication ddf version to 2.21.4
@kcover @peterhuffer @aaronilovici
Verify install and basic replication
=> ddf version update to 2.21.4

dependency-check-maven-config.xml, distributions/osgi/features/replication/pom.xml, pom.xml, replication-commands/pom.xml
Fixes Owasp findings.
CI build
Fixes #XXXX
=> Fix owasp findings

pom.xml
Modifies the maven pom to use the office mirror of the NVD database.
@chrasmussen 
@shaundmorris 
@TonyMorrison 
@LinkMJB 
CICD should pass
Fixes #XXXX
- [N/A] Documentation Updated
- [N/A] Update / Add Unit Tests
- [N/A] Update / Add Integration Tests
=> Modify the owasp plugin to use the phx office nvd mirror

dependency-check-maven-config.xml, pom.xml
Provides upgraded versions for Karaf, Commons, Guava, CXF, Jetty, Awaitally, and a variety of maven plugins.
@cjlange
@clockard 
@mdang8
Pull branch, full build with tests.
=> Upgrading a variety of dependencies for 0.3.x replication
